version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-learning-logs:p20
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1 